### ISSUE TITLE
[Feature]: import all playlist liked by a user

### ISSUE THREAD

**Issue by Leptopoda** [Zibbp/tidal-utils#2]
What about the feature to add a user ID and let the tool import all playlists liked by a user.
This would make it easier to batch migrate playlists from spotify

**Comment by Zibbp** [comment]
Great idea, I'm not going to promise it will happen but I will take a look at it.

**Comment by Zibbp** [comment]
Progress can be tracked in #5

**Comment by Zibbp** [comment]
Feature has been added in [release v1.0.0](https://github.com/Zibbp/tidal-utils/releases/tag/v1.0.0). Closing.
